# Generated by Django 3.2.9 on 2021-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(default='Mofe', max_length=40),
        ),
    ]
