# Generated by Django 3.2.9 on 2021-11-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
    ]
