# Generated by Django 3.2.9 on 2021-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_mymodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.CharField(choices=[('A', '<10'), ('B', '10 - 20'), ('C', '21 - 30')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1),
        ),
    ]
