# Generated by Django 3.1.13 on 2021-11-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20211118_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='youModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image_upload',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to='images/'),
        ),
    ]
