# Generated by Django 3.2.9 on 2021-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20211123_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
