# Generated by Django 3.2.9 on 2021-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_mymodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
    ]
