# Generated by Django 3.2.9 on 2021-11-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_mymodel_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image_upload',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to='images/'),
        ),
    ]
