# Generated by Django 3.2.9 on 2021-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_mymodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='a_k_a',
            field=models.CharField(default='Mofe', max_length=20),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='age',
            field=models.CharField(choices=[('A', '<10'), ('B', '10 - 20'), ('C', '21 - 30')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='area',
            field=models.CharField(default='Mofe', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='city',
            field=models.CharField(default='Mofe', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='contact_name',
            field=models.CharField(default='Mofe', max_length=40),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='contact_person_address',
            field=models.CharField(default='Mofe', max_length=40),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='contact_person_email',
            field=models.CharField(default='django@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='date_declared_missing',
            field=models.DateField(default=0.0004948045522018803),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.CharField(default='Mofe@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(default='Mofe', max_length=40),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='height',
            field=models.CharField(default=12, max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='last_known_address',
            field=models.CharField(default='akjdfk', max_length=40),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='last_name',
            field=models.CharField(default='Mofe', max_length=40),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='other_names',
            field=models.CharField(default='Mofe', max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(default='08020310445', max_length=11),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='state',
            field=models.CharField(default='Mofe', max_length=30),
        ),
    ]
